apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentcreator-cr
rules:
  - apiGroups:
      - hardik.dev
    resources:
      - deploymentcreators
    verbs:
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deploymets
    verbs:
      - get
      - create
      - update
      - delete
