apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploymentcreator-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploymentcreator-cr
subjects:
  - kind: ServiceAccount
    name: deploymentcreator-sa
    namespace: default
